### ISSUE TITLE
Cant use latest JDA Version

### ISSUE THREAD

**Issue by RzR32** [RzR32/Discord_Bot-RzR32_Bot#23]
Cant run the Bot with the latest JDA Version (JDA:4.1.1_111 and above...).

If I try to start the bot in Intelij it start but if I start it as .jar, the following error occurs:
 
`Exception in thread "main" java.lang.NoSuchMethodError: 'net.dv8tion.jda.api.JDABuilder net.dv8tion.jda.api.JDABuilder.createDefault(java.lang.String) 'at Main.main(Main.java:44)`

 - (Main.java:[44](https://github.com/RzR32/Discord_Bot-RzR32_Bot/blob/testing/src/main/java/Main.java#L44))
- [JDA ](https://github.com/DV8FromTheWorld/JDA/wiki/3%29-Getting-Started#connecting-to-discord-with-a-bot-account)(create Bot)

**Comment by johanneslosch** [comment]
I tested it on my Mac and I got this error:

> johannes@Johannes discord_bot_jar % java -jar discord-bot.jar jar   
21:50:53.291 [main] INFO main - --------------------------------------------------
21:50:53.293 [main] ERROR main - null
Exception in thread "main" java.lang.NullPointerException
	at other.LogBack.removeANSICodefromLOG(LogBack.java:41)
	at other.LogBack.log(LogBack.java:34)
	at Main.main(Main.java:96)

[My Output-file with release 4.1.1_121](https://github.com/RzR32/Discord_Bot-RzR32_Bot/files/4351339/discord-bot.jar.zip)

**Comment by johanneslosch** [comment]
I tested it with my Windows PC (Java 12) and this was the error:

> λ java -jar discord-bot.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by johanneslosch** [comment]
Somewhere at [Line 96 in Main](https://github.com/RzR32/Discord_Bot-RzR32_Bot/blob/28a920a896741b230cc1fd9921849fcab47e4539/src/main/java/Main.java#L96) could be a result from AccountBuilder

**Comment by johanneslosch** [comment]
if I replace the Line 96 with a `System.out.println()` is the result `null`

**Comment by RzR32** [comment]
I think I found my error - I create a Artifact to have my bot as .jar but my error was I "extracted my bot with a old JDA version 108 or so - now it works (mostly)

It seems like you can't access all members as a list, this make many things unusable ... like GamePlayingCount, Members, Name_Change, Member_join_leave, ... (maybe new Issues?)

**Comment by RzR32** [comment]
Now I found why the other users wasn´t displayed ... I must check two things on the "Discord Developer Portal" to use the feature (see image below) > now it works!
![image](https://user-images.githubusercontent.com/46526880/77112422-4611da80-6a29-11ea-8fd1-f37268c63140.png)
